### ISSUE TITLE
如何加载进程或者说win10没效果？

### ISSUE THREAD

**Issue by adzcsx2** [lxfly2000/SpeedGear2#1]

**Comment by adzcsx2** [comment]
直接先开SPEEDGEAR 64或者86，再开测试程序，再点开启，之后没效果，变速进程也没有。

**Comment by lxfly2000** [comment]
你测试的是什么程序？有些逻辑过于复杂的程序是没法用的

**Comment by login404** [comment]
这个是怎么用的?
变速进程的列表右键没有菜单
把exe拖到列表框上也不会添加
