### ISSUE TITLE
请问有Ubuntu 版本的么

### ISSUE THREAD

**Issue by DaBaiTuu** [lxfly2000/SpeedGear2#5]
如题，抱歉写在 issue里，没地方了，见谅

**Comment by lxfly2000** [comment]
没有

**Comment by DaBaiTuu** [comment]
那请问你知道有ubuntu 下类似功能的变速齿轮么

> 没有

**Comment by lxfly2000** [comment]
这个变速功能一般是给游戏用的，Ubuntu在游戏上的应用比较少，所以没有这种东西

**Comment by DaBaiTuu** [comment]
> 这个变速功能一般是给游戏用的，Ubuntu在游戏上的应用比较少，所以没有这种东西

好的谢谢，不过正是在下准备在 ubuntu下玩游戏， 是仙剑1的改版，因为是工作时的电脑（摸鱼），所以没办法。
